# version: 0.1

# environment_variables:
  # plaintext:
  #   DJANGO_SETTINGS_MODULE: config.settings.test
  #   SECRET_KEY: nosecret
  #   DATABASE_DEFAULT_URL: sqlite:///db1.sqlite3
  #   DATABASE_STREAMDATA_URL: sqlite:///db2.sqlite3
  #   STREAM_INCOMING_PRIVATE_KEY: changeme
  #   STREAM_INCOMING_PUBLIC_KEY: changeme
  #   GOOGLE_API_KEY: changeme
  #   OPBEAT_ENABLED: False

version: 0.2

phases:
  install:
    commands:
      - pip install --upgrade pip
      - apt-get update && apt-get install -y build-essential python3-dev libjpeg-dev zlib1g-dev libfreetype6-dev
  pre_build:
    commands:
      - pip install --only-binary :all: ruamel.yaml Pillow
  build:
    commands:
      - pip install -r requirements.txt
      - gunicorn --daemon --workers 3 --bind 0.0.0.0:8000 blogprojectdrf.wsgi:application
 
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - '**/*'
